/** @format */
"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { darkTheme } from "./muiprovider";
import LocalizationProviderHelper from "./LocalizationProviderHelper";
import { Provider } from "react-redux";
import { store } from "@/store/rootStore";
import SocketWrapperHelper from "./SocketWrapperHelper";
import LayoutWrapper from "./LayoutWrapper";
import "../theme-variables.css";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });
/* 
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}; */

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<title>foofoo</title>
			<LocalizationProviderHelper>
				<Provider store={store}>
					<ThemeProvider theme={darkTheme}>
						<SocketWrapperHelper>
							<LayoutWrapper>
								<CssBaseline />
								<body className={inter.className}>{children}</body>
							</LayoutWrapper>
						</SocketWrapperHelper>
					</ThemeProvider>
				</Provider>
			</LocalizationProviderHelper>
		</html>
	);
}
